numpy计算的优越性
对比计算时间节省10-100倍

In [ ]:
%time?

In [5]:
import numpy as np

In [6]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [8]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 34.9 ms


In [9]:
%time for _ in range(10): my_list2 = my_list * 2

Wall time: 378 ms


ndarray 多维数组对象.是一个多维的同类数据组合的容器

In [11]:
data = np.random.randn(2, 3)
data 

array([[-0.6346061 ,  0.11952679, -0.66428953],
       [ 0.21062029, -0.29035252,  1.06084023]])

In [14]:
data.shape
data.dtype

numpy.dtype[float64]

In [16]:
data[0].shape

(3,)

生成ndarray最简单的方法是使用array函数，array函数接收序列型对象，也包括张量.
除非显式指定，否则array方法自动推断数据类型
也可以用ones,zeros,empty来创建新张量，若想创建高维张量，必须使用元组来制定形状
np.arange可看成是python内建range数组的张量版

In [18]:
data1 = [6, 7.5, 8, 0, 1]

In [19]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [22]:
arr1.ndim
arr1.shape
arr1.dtype

dtype('float64')

In [24]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [25]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

数组生成函数

In [27]:
np.ones_like(data)

array([[1., 1., 1.],
       [1., 1., 1.]])

ndarray的数据类型

In [28]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)

In [29]:
arr1.dtype
arr2.dtype

dtype('int32')

In [30]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [31]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')