In [1]:
import numpy as np

张量的显式方法astypr转化张量的数据类型，*不改变*原本张量的数据类型
也可用张量dtype属性作为变量直接指定数据类型

In [ ]:
arr = np.arange(5)

In [11]:
arr.dtype

dtype('int32')

In [9]:
arr.astype(np.float64)

array([0., 1., 2., 3., 4.])

In [14]:
float_arr = arr.astype(np.float64)

In [12]:
int_arr = np.arange(10)

In [16]:
int_arr.astype(float_arr.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

numpy张量算术
张量可以让你无需使用for循环，这称为向量化来实现批量操作
标量计算应用到相应的每个元素之间
同尺寸张量的比较返回一个布尔值张量
不同尺寸的张量运算时会用到广播机制

In [25]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [19]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [20]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [22]:
arr2 = np.ones((2, 3))

In [28]:
arr == arr2

array([[ True, False, False],
       [False, False, False]])

基础（一维）索引和切片
numpy的切片不是对原数据的复制，而是原数据本身的视图。对于视图的修改，最终会反映到原数据上。
[:]表示对原张量所有数据的引用
对于python内建列表，切片引用不会跟随原数据变化，列表间直接赋值相等则会同时变化
通过索引可以将标量或者数组传递给张量对应位置

In [29]:
arr = np.arange(10)
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[5:8]

array([5, 6, 7])

In [31]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
arr_slice = arr[5:8]
arr_slice[:]= 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [33]:
arr1 = arr[5:8].copy()

In [34]:
print(id(arr),id(arr1))

1595396022896 1595396026256


In [39]:
list1 = [1,2,3]
list2 = list1[0]
list1[0] = 22
print("list1:",list1,"list2:",list2)

list1: [22, 2, 3] list2: 1


In [40]:
arr2d = np.ones((2,3))

In [41]:
arr2d[0]

array([1., 1., 1.])

In [42]:
arr2d[0][2] == arr2d[0,2]

True

In [43]:
arr3d = np.ones((2, 3, 3))

In [44]:
arr3d[0]

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
arr3d[0] = np.array([[1, 2, 3],[6, 3 ,9],[1, 5, 9]])

In [47]:
arr3d[0]

array([[1., 2., 3.],
       [6., 3., 9.],
       [1., 5., 9.]])

张量（>=2维）的切片索引
切片不改变结果的形状，与原形状相同
索引会降低一个维度
两者可以同时使用，获取想要的形状的张量

In [48]:
arr2d = np.array([[1, 2, 3],[4, 5 ,6],[7, 8, 9]])

In [52]:
arr2d[:0]

array([], shape=(0, 3), dtype=int32)

In [58]:
arr2d[0:1,0:1]

array([[1]])

In [61]:
arr2d[1,0:2]

array([[4, 5]])

In [56]:
arr2d[0:2, 2]

array([3, 6])

布尔索引
索引数组传入布尔值数组时，布尔数组必须和张量轴索引长度相同
布尔索引结果形状不变
可以使用!=或者~来对条件取反
取多个名字时可以使用多个布尔条件来联合
python的关键字and和or对布尔值张量没用，请使用&和|。反过来，前者对内建列表对象有用，后者则无作用。

In [72]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [63]:
data = np.random.randn(7,4)

In [64]:
data

array([[ 0.04301779, -1.5953848 , -0.39034148, -1.14851704],
       [ 1.09766648,  0.21120759, -0.32184212,  0.1399054 ],
       [-0.0471954 ,  0.24007509, -0.13242673,  0.04882366],
       [-1.55084153, -0.15244676,  0.96142847,  0.4193185 ],
       [ 0.05348307, -1.94768598, -0.40822546,  1.30043639],
       [-1.64372482, -1.03741432,  0.25460021, -0.481478  ],
       [-1.15979863, -0.31202699,  1.48225765,  0.79873628]])

In [65]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [66]:
data[names == 'Bob']

array([[ 0.04301779, -1.5953848 , -0.39034148, -1.14851704],
       [-1.55084153, -0.15244676,  0.96142847,  0.4193185 ]])

In [67]:
name1 = names == 'Bob'

In [70]:
name1

array([ True, False, False, False, False, False, False])

In [69]:
name1[3] = False

In [71]:
data[name1]

array([[ 0.04301779, -1.5953848 , -0.39034148, -1.14851704]])

In [73]:
data[~(names == 'Bob')]

array([[ 1.09766648,  0.21120759, -0.32184212,  0.1399054 ],
       [-0.0471954 ,  0.24007509, -0.13242673,  0.04882366],
       [ 0.05348307, -1.94768598, -0.40822546,  1.30043639],
       [-1.64372482, -1.03741432,  0.25460021, -0.481478  ],
       [-1.15979863, -0.31202699,  1.48225765,  0.79873628]])

In [75]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [77]:
[True,True] or [False, False]

TypeError: unsupported operand type(s) for |: 'list' and 'list'

In [78]:
data < 0

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True, False,  True, False],
       [ True,  True, False, False],
       [False,  True,  True, False],
       [ True,  True, False,  True],
       [ True,  True, False, False]])

In [79]:
data[data < 0] = 0
data

array([[0.04301779, 0.        , 0.        , 0.        ],
       [1.09766648, 0.21120759, 0.        , 0.1399054 ],
       [0.        , 0.24007509, 0.        , 0.04882366],
       [0.        , 0.        , 0.96142847, 0.4193185 ],
       [0.05348307, 0.        , 0.        , 1.30043639],
       [0.        , 0.        , 0.25460021, 0.        ],
       [0.        , 0.        , 1.48225765, 0.79873628]])

In [80]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.09766648, 0.21120759, 0.        , 0.1399054 ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.25460021, 0.        ],
       [0.        , 0.        , 1.48225765, 0.79873628]])

神奇索引
索引输入整数数组，这称为神奇索引
目的是为选取特意顺序的子集
索引为多个数组时，最后可能挑选出对应前一个索引元组的对应元素
神奇索引总是复制新的元素

In [81]:
arr = np.empty((8, 4))
arr

array([[7.88212187e-312, 1.03259720e-321, 0.00000000e+000,
        0.00000000e+000],
       [1.69119330e-306, 5.02034658e+175, 3.76240029e+179,
        7.11056605e-038],
       [2.54577426e-052, 1.42554121e+160, 4.95230291e-062,
        2.16385130e+190],
       [1.94918964e-153, 5.30581644e+180, 4.31999742e-096,
        2.14027814e+161],
       [1.47762371e+248, 4.30625279e-096, 4.82337723e+228,
        9.95645909e-043],
       [5.34163038e-038, 4.28357485e-037, 2.17564134e-076,
        4.30332327e-096],
       [1.16097020e-028, 1.26071127e-076, 3.05305390e-028,
        1.89812950e-052],
       [1.04917183e-153, 9.08366791e+223, 6.14415221e-144,
        4.06325763e-317]])

In [82]:
for i in range(8):
    arr[i] = i

In [83]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [84]:
data[[0,1]]

array([[7.        , 7.        , 7.        , 7.        ],
       [1.09766648, 0.21120759, 0.        , 0.1399054 ]])

In [86]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [87]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [88]:
arr = np.arange(12).reshape((2,2,3))
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [91]:
arr[[0],[0]]

array([[0, 1, 2]])

In [92]:
arr[[0]]

array([[[0, 1, 2],
        [3, 4, 5]]])

数轴转置和换轴

In [93]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [94]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

常见练习

In [7]:
arr = np.random.randn(2,3)

In [8]:
arr

array([[-0.64350769,  1.10504293,  0.26463066],
       [-1.03274828, -2.28739941,  0.32573097]])

In [11]:
arr.mean(1)

array([ 0.2420553 , -0.99813891])